services:
  db:
    image: postgres:16
    container_name: equals_db
    environment:
      POSTGRES_DB: equals
      POSTGRES_USER: equals
      POSTGRES_PASSWORD: equals
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: